apiVersion: v1
kind: Pod
metadata:
  name: nginx-healthcheck
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-demo
    image: nginx
    ports:
    - name: nginx-port
      containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 30
      periodSeconds: 30
