apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-local-pvc
  labels:
    app: wordpress
    #tier: back-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
