apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
    tier: frontend
spec:
  ports:
  - port: 31000
    nodePort: 31000
    targetPort: wordpress-port
    protocol: TCP
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
