apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-local-pvc
  labels:
    app: wordpress
    #tier: back-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
