apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring
  labels:
    app: monitoring
spec:
  selector:
    matchLabels:
      name: monitoring
  template:
    metadata:
      labels:
        name: monitoring
    spec:
      containers:
      - name: monitoring
        image: nginx
